import { inter } from '@/app/ui/fonts';

import '@/app/ui/global.css';

export const metadata = {
  title: 'Dashboard App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
